### ISSUE TITLE
React modal not applying the theme properly using next-themes

### ISSUE THREAD

**Issue by jeremy-babylonchain** [babylonchain/simple-staking#82]
![CleanShot 2024-05-17 at 01 19 42@2x](https://github.com/babylonchain/simple-staking/assets/168515712/e1efb54a-10f6-4996-92a3-72c439385b1b)

Noticed the react-modal sometimes is not reactive to the main div theme switches. Resulting in white text and white background.

**Comment by gbarkhatov** [comment]
Additional info - I have a feeling that this is happening because of how our tailwind theme works and where this `react-responsive-modal` renders. 
It has a prop https://react-responsive-modal.leopradel.com/#custom-container to render inside the custom container. We can do it inside the `<main>` block of our application. Should solve an issue?
